#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: $0 [-d <left-dir>] <right-dir>/<file> [<left-dir>]"
    exit 1
fi


while getopts ":d:" opt; do
  case $opt in
    d)
      left="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
  esac
done
shift $(expr $OPTIND - 1 )

right="$1"

if [ -z "$left" ]; then
  left=${2:-.}
fi

if [ ! -e "$right" ]; then
  echo "Error: '$right' does not exist."
  exit 1
fi

if [ ! -d "$left" ]; then
  echo "Error: '$left' is not a directory."
  exit 1
fi


file=$(basename "$right")
nvim -d "$left"/"$file" "$right"
