# zsh: need to export LC_ALL=en_US.UTF-8 for RPROMPT with unicode char

# needs stty -ixon -ixoff
unbind C-b
set -g prefix ^S

# set own TERM variable
set -g default-terminal "tmux-256color"

# enable xterm keys
set-window-option -g xterm-keys 
set-option -g focus-events on

# scrollback
set -g history-limit 100000

# Add key timing optimizations:
set -sg repeat-time 300
set -sg escape-time 0

# For iterm2 integration specifically:
set -ga terminal-overrides ",*256col*:Tc"

# avoid mouse inserting chars into window
set -g mouse off

# needs .ssh/rc to set up symlink
set-environment -g 'SSH_AUTH_SOCK' ~/.ssh/ssh_auth_sock
